apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: ts-observability
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
